### ISSUE TITLE
Changes are not saved Returns

### ISSUE THREAD

**Issue by vulgerrity** [ieatacid/OctoPrint-GcodeEditor#31]
The issue from Issue #5 seems to have returned.  I cannot save Gcode to files that are in sub directories, but I can edit GCode files in the root directory only.  When trying to save in a subdirectory the console reports a Post error 415 (UNSUPPORTED MEDIA TYPE).

**Comment by vulgerrity** [comment]
I was able to confirm that the solution [here](https://github.com/ieatacid/OctoPrint-GcodeEditor/issues/28) works in OctoPrint 1.7.3

**Comment by Build-0-Matic** [comment]
But it sadly stopped working 0n version 1.8.0

**Comment by coelholm** [comment]
Check on that https://github.com/ieatacid/OctoPrint-GcodeEditor/issues/33#issuecomment-1407159709

**Comment by TylonHH** [comment]
works for me: https://github.com/ieatacid/OctoPrint-GcodeEditor/releases/tag/0.2.13

**Comment by 7s3** [comment]
I'm also having this problem in GcodeEditor 0.2.14
