### ISSUE TITLE
cant save because name is wrong read

### ISSUE THREAD

**Issue by TylonHH** [ieatacid/OctoPrint-GcodeEditor#33]
Hey
as you can see in the picture, the name of the file is wrong. I have to correct the filename to save.
![grafik](https://user-images.githubusercontent.com/18073299/171951787-7ef4e6d7-2cfb-4024-9d89-c82375d87d8f.png)
Im on OctoPrint Version 1.8.1
cheers

**Comment by coelholm** [comment]
I may have find the solution, did not extensively tested, but it is working. Pull request #37

**Comment by coelholm** [comment]
Filename is retrieved with command:
`var fname = button.parent().parent().children('div.title').html();`

I believe that div titles got an update from octoprint or another plugin. That update included an "<i class ...." statement creating an issue. Changing from .html() to .text() solved the problem. I've created a pull request #37, if you can test it and post your comments would be great.
You can also try to update ~/oprint/lib/python3.7/site-packages/octoprint_GcodeEditor/static/js/GcodeEditor.js and make that line looks like bellow:
`var fname = button.parent().parent().children('div.title').text();`. 

Don't forget to restart octoprint.

**Comment by TylonHH** [comment]
https://github.com/ieatacid/OctoPrint-GcodeEditor/releases/tag/0.2.13
